name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies.
        run: yarn
      - name: Run the project
        run: |
          yarn build,
          yarn test
      - name: Code linting
        run: |
          yarn add eslint,
          npx eslint .
